### ISSUE TITLE
Optimize BbRest swagger_json initialization

### ISSUE THREAD

**Issue by scollovati** [mdeakyne/BbRest#3]
Hi, 
since in the class inizialization you grab the BB version, wouldn't be better to build the right swagger url with the version coded inside (like `/portal/docs/apis/learn-swagger-3700.0.0.json` )?

In this way the attribute `__all_functions` stores only the API methods available.

**Comment by mdeakyne** [comment]
You'd think so - but they started including depreciated APIs into the same swagger.json, and I didn't take the time to figure out how to filter those out.  I moved to that approach at one point, but it broke for that reason which exacerbated the multiple names issue. 

GetClasses v1. GetClasses v2. overwrote each other, even when one was deprecated.  

It's a good point, and I need to revisit it. Thank you.
