### ISSUE TITLE
Post method does not allow query parameters

### ISSUE THREAD

**Issue by bartPrzybysz** [mdeakyne/BbRest#4]
When calling a bbrest method for a POST endpoint, the program outputs an unexpected argument message if I include query parameters.
In this particular case, I need to set both the POST and GET parameters in order to add an item to a child course.

```python
from bbrest import BbRest

KEY = '~~~'
SECRET = '~~~'
URL = '~~~'

bb = BbRest(KEY, SECRET, URL)

payload = {
    'title': 'Item',
    'body': '<p>Item Content</p>',
    'parentId': '~~~',
    'contentHandler': {'id': 'resource/x-bb-document'}
}

bb.CreateChild(courseId=course_id, 
               contentId=content_id, 
               params={'allowChildCourseContent': True}, 
               payload=payload)
```

outputs
```
TypeError: CreateChild() got an unexpected keyword argument 'params'
```

**Comment by mdeakyne** [comment]
Good catch. I guess I assumed that all settings would be included in a payload, rather than in a distinct parameters.  I think I can alter this to allow for all methods to accept parameters optionally, but let me think through if there is a better way.

**Comment by bartPrzybysz** [comment]
Thank you so much! I appreciate the quick response!

**Comment by mdeakyne** [comment]
Corrected with latest commit.
